### ISSUE TITLE
dataset release

### ISSUE THREAD

**Issue by zxg043017** [BioMedIA-MBZUAI/MedPromptX#1]
Hello, when the MedPromptX-VQA dataset will be release?

**Comment by Mai-CS** [comment]
Hi, MedPromptX-VQA is built on HAIM, MIMIC-CXR and MIMIC-IV. So if you have PhysioNet credentials, then you can use the preprocessing code that I will share.

**Comment by Mai-CS** [comment]
It is available now.

**Comment by zxg043017** [comment]
Thanks for releasing your dataset. Additionally, can you provide your code for pretraining or finetune?

**Comment by Mai-CS** [comment]
Our model is based on few-shot prompting where no fine-tuning or pre-training is needed. You can find the implementation in `main.py`.
